### ISSUE TITLE
Cannot delete a site (or shop)

### ISSUE THREAD

**Issue by drkNsubuga** [aimeos/ai-laravel#12]
An error shows when a shop or site is deleted.

### **Environment**
Aimeos-laravel: "2021.10.*",

### **Error shown**
Required parameter 'id' is missing
 
### **Steps to reproduce**
![image](https://user-images.githubusercontent.com/12871099/143548031-6221725c-e3c8-40c0-96e8-fad51d92df12.png)

**Comment by aimeos** [comment]
Thank you for your issue report!

Problem has been fixed and you can test after executing:
```
composer req aimeos/ai-admin-jqadm:2021.10.x-dev
```

**Comment by drkNsubuga** [comment]
Thank for the quick feedback
