### ISSUE TITLE
Laravel 8 migrations

### ISSUE THREAD

**Issue by mylgeorge** [aimeos/ai-laravel#8]
Laravel 8 uses bigint in default migrations for user id used by aimeos for customer.

Any plans on making this compatible.

i think this changes in customer shema can work.

ext/ai-laravel/lib/custom/setup/default/schema/customer.php:18
```
$table->addColumn( 'id', 'bigint', array( 'autoincrement' => true, 'unsigned' => true ) );
``` 
ext/ai-laravel/lib/custom/setup/default/schema/customer.php:70

```
$table->addColumn( 'parentid', 'bigint', ['unsigned' => true] );
```
ext/ai-laravel/lib/custom/setup/default/schema/customer.php:144
```
$table->addColumn( 'parentid', 'bigint', ['unsigned' => true] );
```
ext/ai-laravel/lib/custom/setup/default/schema/customer.php:201
```
$table->addColumn( 'parentid', 'bigint', ['unsigned' => true] );
```

**Comment by aimeos** [comment]
Don't know why they use bigint now but if you create a PR with the change, we will merge it.

**Comment by aimeos** [comment]
It's merged now, thanks again!
